### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by usmonster**

### CODE REVIEW

**Comment by nanis94** [comment]
usmonster:typo-fix master

**Review by nanis94 — COMMENTED** [review]
master

**Comment by nanis94** [comment]
master

**Comment by nanis94** [comment]
usmonster:typo-fix

**Comment by lafkpages** [comment]
LGTM 👍

**Comment by usmonster** [comment]
OK to merge this tiny thing, @isaacs? 😄

**Pull request merged**
