### PR TITLE
fix(brace-expansion): ignore only blocks that begins with $

### PR DESCRIPTION
**Pull request by roggervalf**
this pr upgrades brace-expansion package that has this fix

### CODE REVIEW

**Comment by roggervalf** [comment]
Please @isaacs when you get some chance could you review this pr?

**Comment by isaacs** [comment]
This doesn't seem like correct behavior, though.

```
$ echo {a,b}\${c,d}\${e,f}
a$c$e a$c$f a$d$e a$d$f b$c$e b$c$f b$d$e b$d$f
```

Minimatch doesn't do ${} expansion, only {,,} expansion.  Ignoring ${} sections seems wrong, no?

**Comment by roggervalf** [comment]
> This doesn't seem like correct behavior, though.
> 
> ```
> $ echo {a,b}\${c,d}\${e,f}
> a$c$e a$c$f a$d$e a$d$f b$c$e b$c$f b$d$e b$d$f
> ```
> 
> Minimatch doesn't do ${} expansion, only {,,} expansion. Ignoring ${} sections seems wrong, no?

@isaacs from your example, I could reproduce it, you are right, it seems this is a bug in brace-expand that do not consider when \$ is present and I created a pr to fix it https://github.com/juliangruber/brace-expansion/pull/58

**Comment by isaacs** [comment]
I don't think that brace-expand should be doing anything with $ at all, escaped or not.  https://github.com/juliangruber/brace-expansion/pull/58#issuecomment-1031960969

**Pull request closed without merging**
